Caronusp/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static 
from django.views.generic import TemplateView
from django.urls import path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('accounts/', include('accounts.urls')),
    path('condutor/', include('condutor.urls')),
    path('passageiro/', include('passageiro.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls')),
    path('react/', TemplateView.as_view(template_name='front-end/index.html')),
    path('api/v1/', include('api.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('<int:usuario_id>/', views.afterlogin, name='afterlogin'),
    path('signup/condutor/<int:usuario_id>/', views.signCondutor, name='condutor'),
    path('signup/passageiro/<int:usuario_id>/', views.signPassageiro, name='passageiro'),
    path('loginredirect/', views.my_view, name='loginredirect')
]

api/urls.py
from django.urls import path
from .views import CaronaDetail, CaronaList

urlpatterns = [
    path('carona/<int:pk>/', CaronaDetail.as_view()),
    path('carona/', CaronaList.as_view()),
]

chat/urls.py
from django.urls import path
from .views import chat_corrida

app_name = 'chat'

urlpatterns = [
    path('<int:usuario_id>/chat_corrida/<int:corrida_id>/<int:type_actor>', chat_corrida, name='chat_corrida'),
]

passageiro/urls.py
from django.urls import path

from . import views

app_name = 'passageiro'

urlpatterns = [
    path('<int:usuario_id>/', views.initial, name='initial'),
    path('<int:usuario_id>/edit/', views.UpdateView, name='edit'),
    path('<int:usuario_id>/search/', views.Search_RequestView, name='search'),
    path('<int:usuario_id>/request/<int:corrida_id>/', views.Search_RequestView, name='request'),
    path('<int:usuario_id>/list/<str:aceito>/', views.ListView, name='list-accepted'),
    path('<int:usuario_id>/list/<str:aceito>/', views.ListView, name='list-requested'),
    path('<int:usuario_id>/list/<str:aceito>/', views.ListView, name='list-rejected'),
    path('<int:usuario_id>/list/<str:aceito>/', views.ListView, name='list-ended'),
    path('<int:usuario_id>/notificacoes/<int:notificacao_id>', views.read_notificacao, name='read_notificacao'),
    path('<int:usuario_id>/racedetail/<int:corrida_id>/', views.DetailView, name='detail'),
    path('<int:usuario_id>/leave/<int:corrida_id>/', views.LeaveView, name='leave'),
    path('<int:usuario_id>/in/<int:corrida_id>/rates/', views.AvaliacaoView, name='rate'),
    path('<int:usuario_id>/condutordetail/<int:condutor_id>', views.condutordetail, name='condutordetail'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager

class UsuarioManager(BaseUserManager):
    use_in_migrations = True

    def create_user(self, email, username, password, **extra_fields):
        if not email:
            raise ValueError('Users must have an email address')
        user = self.model(email=self.normalize_email(email), username=username,  **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is False:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is False:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(email, username, password, **extra_fields)
    
class Usuario(AbstractUser):
    telefone = models.CharField(max_length=11)
    RG = models.CharField(max_length=9)
    foto = models.ImageField(upload_to="uploads/")
    is_condutor = models.BooleanField(default=False)
    is_passageiro = models.BooleanField(default=False)
    objects = UsuarioManager()
    
class Condutor(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    nota_media = models.FloatField()
    CNH = models.CharField(max_length=11)
    
    def __str__(self):
        return f'"{self.id}" - {self.usuario}'
    
class Passageiro(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    nota_media = models.FloatField()
    
    def __str__(self):
        return f'"{self.id}" - {self.usuario}'
    
class Carona(models.Model):
    condutor = models.ForeignKey(Condutor, on_delete=models.CASCADE)
    local_partida = models.TextField()
    endereco_partida = models.TextField()
    placeId_partida = models.TextField()
    local_chegada = models.TextField()
    endereco_chegada = models.TextField()
    placeId_chegada = models.TextField()
    horario_partida = models.TimeField()
    horario_chegada = models.TimeField()
    lugares = models.IntegerField()
    placa_veiculo = models.CharField(max_length=7)

    def __str__(self):
        return f'"{self.id}" - {self.condutor} - {self.local_partida} - {self.local_chegada} - {self.horario_partida} - {self.horario_chegada} - {self.lugares} - {self.placa_veiculo}'
    
class Corrida(models.Model):
    carona = models.ForeignKey(Carona, on_delete=models.CASCADE)
    dia = models.DateField()
    ativa = models.BooleanField()
    vagas = models.IntegerField()

    def __str__(self):
        return f'"{self.id}" - {self.carona} - {self.dia} - {self.ativa} - {self.vagas}'

class Passageiros_corrida(models.Model):
    passageiro = models.ForeignKey(Passageiro, on_delete=models.CASCADE)
    corrida = models.ForeignKey(Corrida, on_delete=models.CASCADE)
    aceito = models.BooleanField(null=True)

    def __str__(self):
        return f'"{self.id}" - {self.passageiro} - {self.corrida} - {self.aceito}'

class Avaliacao_Condutor(models.Model):
    avaliador = models.ForeignKey(Passageiro, on_delete=models.CASCADE)
    avaliado = models.ForeignKey(Condutor, on_delete=models.CASCADE)
    corrida = models.ForeignKey(Corrida, on_delete=models.CASCADE)
    nota = models.IntegerField()

    def __str__(self):
        return f'"{self.id}" - {self.avaliador} - {self.avaliado} - {self.corrida} - {self.nota}'
    
class Avaliacao_Passageiro(models.Model):
    avaliador = models.ForeignKey(Condutor, on_delete=models.CASCADE)
    avaliado = models.ForeignKey(Passageiro, on_delete=models.CASCADE)
    corrida = models.ForeignKey(Corrida, on_delete=models.CASCADE)
    nota = models.IntegerField()

    def __str__(self):
        return f'"{self.id}" - {self.avaliador} - {self.avaliado} - {self.corrida} - {self.nota}'
    
class Mensagem(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    corrida = models.ForeignKey(Corrida, on_delete=models.CASCADE)
    texto = models.TextField()
    hora = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'"{self.id}" - {self.usuario} - {self.corrida} - {self.texto} - {self.hora}'
    
class Notificacao(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    texto = models.TextField()
    hora = models.DateTimeField(auto_now_add=True)
    visto = models.BooleanField(default=False)
    para_condutor = models.BooleanField()

    def __str__(self):
        return f'"{self.id}" - {self.usuario} - {self.texto} - {self.hora} - {self.visto} - {self.para_condutor}'

staticpages/models.py
from django.db import models
from django.conf import settings


class Usuario(models.Model):
    # id = models.IntegerField()
    nome = models.CharField()
    email = models.CharField()
    telefone = models.CharField()
    hash_senha = models.CharField()
    RG = models.CharField()
    foto = models.ImageField()

    def __str__(self):
        return f'{self.nome}'

class Passageiro(models.Model):
    # id = models.IntegerField()
    usuario_id = models.ForeignKey(Usuario)
    nota_media = models.FloatField()

    def __str__(self):
        return f'"{self.id}" - {self.usuario_id}'
    
class Condutor(models.Model):
    # id = models.IntegerField()
    usuario_id = models.ForeignKey(Usuario)
    nota_media = models.FloatField()
    CNH = models.IntegerField()

    def __str__(self):
        return f'"{self.id}" - {self.usuario_id}'

class Carona(models.Model):
    # id = models.IntegerField()
    condutor_id = models.ForeignKey(Condutor)
    local_partida = models.CharField()
    local_chegada = models.CharField()
    horario_partida = models.TimeField()
    horario_chegada = models.TimeField()
    lugares = models.IntegerField()
    placa_veiculo = models.CharField()

    def __str__(self):
        return f''
    
class Corrida(models.Model):
    # id = models.IntegerField()
    carona_id = models.ForeignKey(Carona)
    dia = models.DateField()
    ativa = models.BooleanField()
    vagas = models.IntegerField()

    def __str__(self):
        return f''
    
class Passageiros_corrida(models.Model):
    # id = models.IntegerField()
    passageiro_id = models.ForeignKey(Passageiro)
    corrida_id = models.ForeignKey(Corrida)
    aceito = models.BooleanField()

    def __str__(self):
        return f''

class Avaliacao_Condutor(models.Model):
    # id = models.IntegerField()
    avaliador_id = models.ForeignKey(Passageiro)
    avaliado_id = models.ForeignKey(Condutor)
    corrida_id = models.ForeignKey(Corrida)
    nota = models.IntegerField()

    def __str__(self):
        return f''

class Avaliacao_Passageiro(models.Model):
    # id = models.IntegerField()
    avaliador_id = models.ForeignKey(Condutor)
    avaliado_id = models.ForeignKey(Passageiro)
    corrida_id = models.ForeignKey(Corrida)
    nota = models.IntegerField()

    def __str__(self):
        return f''
    
class Mensagem(models.Model):
    # id = models.IntegerField()
    usuario_id = models.ForeignKey(Usuario)
    corrda_id = models.ForeignKey(Corrida)
    texto = models.CharField()
    hora = models.DateTimeField()

    def __str__(self):
        return f''

passageiro/templates/passageiro/detail_condutor.html
{% extends 'base.html' %}

{% block title %}
    Detalhes do condutor
{% endblock %}

{% block content %}
<h1>Detalhes do condutor</h1>
<p>Foto: <img src="{{ condutor.usuario.foto.url }}" style="max-width: 450px; max-height: 300px"></p>
<p>Nome: {{ condutor.usuario.first_name }} {{ condutor.usuario.last_name }}</p>
<p>Telefone: {{ condutor.usuario.telefone }}</p>
<p>Nota: {{ condutor.nota_media }}</p>

<a class="voltar" onclick="history.back()">Voltar</a>
{% endblock %}

passageiro/templates/passageiro/edit.html
{% extends 'base.html' %}

{% block title %}
Editar perfil
{% endblock title %}

{% block content %}
<h1>Atualizar dados do perfil</h1>
<form method="post" enctype="multipart/form-data" action="{% url 'passageiro:edit' usuario.id%}">
  {% csrf_token %}
    <p>
        <label for="id_foto">Foto:</label>
        <img src="{{ usuario.foto.url }}" style="max-width: 450px; max-height: 300px">
        <input type="file" name="foto" id="id_foto"/>
    </p>
    <p>
        <label for="id_username">Nome de usuário:</label>
        <input type="text" name="username" id="id_username" value="{{usuario.username}}" />
    </p>
    <p>
        <label for="id_first_name">Nome:</label>
        <input type="text" name="first_name" id="id_first_name" value="{{usuario.first_name}}" />
    </p>
    <p>
        <label for="id_last_name">Sobrenome:</label>
        <input type="text" name="last_name" id="id_last_name" value="{{usuario.last_name}}" />
    </p>
    <p>
        <label for="id_email">Email:</label>
        <input type="text" name="email" id="id_email" value="{{usuario.email}}" />
    </p>
    <p>
        <label for="id_telefone">Telefone:</label>
        <input maxlength=11 type="text" name="telefone" id="id_telefone" value="{{usuario.telefone}}" />
    </p>
    <p>
        <label for="id_RG">RG:</label>
        <input maxlength=9 type="text" name="RG" id="id_RG" value="{{usuario.RG}}" />
    </p>

    
  
    <button type="submit">Salvar alterações</button>
    <a class="exit" href="{% url 'passageiro:initial' user.id%}">Cancelar</a>
</form>

{% endblock content %}

passageiro/templates/passageiro/initial.html
{% extends 'base.html' %}

{% block title %}
Passageiro
{% endblock title %}

{% block content %}
    <h1>Olá {{ user.first_name }} {{ user.last_name }}! Você está logado como passageiro</h1>
    <h1>Ações</h1>
    <div class="grid">
        <a href="{% url 'passageiro:list-accepted' user.id 'accepted'%}">Minhas corridas</a>
        <p>Aqui você pode ver as corridas aceitas, solicitadas, rejeitadas e finalizadas</p>
        <a href="{% url 'passageiro:search' user.id %}">Procurar corridas</a>
        <p>Buscar corridas de acordo com suas preferências</p>
        <a href="{% url 'passageiro:edit' user.id %}">Editar perfil</a>
        <p>Editar suas informações pessoais</p>
        <a href="{% url 'accounts:afterlogin' user.id %}">Escolher ator</a>
        <p>Voltar para a tela de escolha de login</p>
    </div>
    {% if notificacoes %}
    <h1>Notificações</h1>
        {% for notificacao in notificacoes %}
            <div class="notificacao" >
                <label class="flex"></label>
                <p>{{ notificacao.texto }}</p>
                <a href="{% url 'passageiro:read_notificacao' user.id notificacao.id %}">Marcar como lida</a>
            </div>
        {% endfor %}
    {% endif %}
{% endblock content %}

passageiro/templates/passageiro/leave_race.html
{% extends 'base.html' %}

{% block title %}
Sair da corrida
{% endblock title %}

{% block content %}

  <form class="flex2" method="POST" action="{% url 'passageiro:leave' user.id corrida.id %}">
    {% csrf_token %}
    <p>
      Confirmar - Sair da corrida do dia {{corrida.dia}}?
    </p>
    <button class="exit" type="submit">Sair</button>
  </form>
  <a class="voltar" href="{% url 'passageiro:list-accepted' user.id 'accepted' %}">Voltar para as corridas aceitas</a>
{% endblock content %}

passageiro/templates/passageiro/list.html
{% extends 'base.html' %}

{% block title %}
Minhas corridas
{% endblock title %}

{% block content %}
<h1>Lista de corridas {{ title }}</h1>
<div class="flex">
    <a href="{% url 'passageiro:list-accepted' user.id 'accepted' %}">Aceitas</a>
    <a href="{% url 'passageiro:list-requested' user.id 'requested' %}">Solicitadas</a>
    <a href="{% url 'passageiro:list-rejected' user.id 'rejected' %}">Rejeitadas</a>
    <a href="{% url 'passageiro:list-ended' user.id 'ended' %}">Finalizadas</a>
</div>
{% if corrida_list %}
<section>
    {% for corrida in corrida_list %}
    <article class="flex">
        <p>Corrida em {{ corrida.dia }} saindo de {{corrida.carona.local_partida}} às {{corrida.carona.horario_partida}} 
            para {{corrida.carona.local_chegada}} às {{corrida.carona.horario_chegada}} || Placa: {{corrida.carona.placa_veiculo}}</p>
            <a href="{% url 'passageiro:detail' user.id corrida.id %}">Ver detalhes</a>
            {% if corrida.aval %} <p> Você avaliou o condutor com nota {{corrida.aval.first.nota}}</p>
            {% elif not corrida.ativa %} <a href="{% url 'passageiro:rate' user.id corrida.id %}">Avaliar</a>{% endif %}
    </article>
    {% endfor %}
</section>
{% else %}
<p>Você não tem corridas para essa categoria</p>
{% endif %}
<a class="voltar" href="{% url 'passageiro:initial' user.id %}">Voltar</a>
{% endblock %}

passageiro/templates/passageiro/race_detail.html
{% extends 'base.html' %}

{% block title %}
Detalhes da corrida
{% endblock title %}

{% block content %}
<h1> Detalhes da corrida </h1>
<h3>
  Dia: {{ corrida.dia }}
  <br>
  Local de partida: {{ carona.local_partida }}  
  <br>
  Horario de partida: {{carona.horario_partida}}
  <br>
  Local de chegada: {{ carona.local_chegada }}  
  <br>
  Horario de chegada: {{carona.horario_chegada}}
  <br>
  Placa: {{carona.placa_veiculo}}
  <br>
</h3>
<div class="flex2">
  <a class="flex" href="{% url 'passageiro:condutordetail' user.id corrida.carona.condutor.id %}">Ver condutor</a>
  {% if corrida.contains and corrida.ativa %}
  <a href="{% url 'chat:chat_corrida' user.id corrida.id 1 %}"> Chat </a>
  <a class="exit" href="{% url 'passageiro:leave' user.id corrida.id %}">Sair da corrida</a>
  {% endif %}
  <a class="voltar" onclick="history.back()">Voltar</a>
</div>
{% endblock content %}

passageiro/templates/passageiro/rate.html
{% extends 'base.html' %}

{% block title %}
Avaliar condutor
{% endblock title %}

{% block content %}

<h1>Avalie o condutor {{corrida.condutor.usuario.first_name}} {{corrida.condutor.usuario.last_name}} 
  em relação a corrida do dia {{corrida.dia}}</h1>


<form method="post" action="{% url 'passageiro:rate' user.id corrida.id %}">
  {% csrf_token %}
  <label for="id_nota">Nota:</label>
  <div class="rating">
    <input type="radio" name="nota" value="5" id="star5" /><label for="star5" title="5 estrelas"></label>
    <input type="radio" name="nota" value="4" id="star4" /><label for="star4" title="4 estrelas"></label>
    <input type="radio" name="nota" value="3" id="star3" /><label for="star3" title="3 estrelas"></label>
    <input type="radio" name="nota" value="2" id="star2" /><label for="star2" title="2 estrelas"></label>
    <input type="radio" name="nota" value="1" id="star1" /><label for="star1" title="1 estrela"></label>
  </div>
  <button type="submit">Avaliar</button>
</form>


<br>
<a class="voltar" href="{% url 'passageiro:list-ended' user.id 'ended' %}">Voltar</a>
{% endblock content %}

passageiro/templates/passageiro/search.html
{% extends 'base.html' %}

{% block title %}
Pesquisar
{% endblock title %}

{% block content %}
<h2>Busca de corridas</h2>
<form action="{% url 'passageiro:search' user.id %}" method="post">
    {% csrf_token %}
    <p>
        <label for="id_dia">Dia:</label>
        <input type="date" name="dia" id="id_dia" min="{% now "Y-m-d" %}" required/>
    </p>
    <p>
        <label for="id_local_partida">Local de partida:</label>
        <input type="text" name="local_partida" id="id_local_partida" required/>
    </p>
    <p>
        <label for="id_local_chegada">Local de chegada:</label>
        <input type="text" name="local_chegada" id="id_local_chegada" required/>
    </p>
    <p>
        <label for="id_horario_chegada">Horário de chegada:</label>
        <input type="time" name="horario_chegada" id="id_horario_chegada" required/>
    </p>
    <button type="submit">Buscar</button>
</form>



<h2>Resultado da busca</h2>
{% if corrida_list %}
<section>
    {% for corrida in corrida_list %}
    <article class="flex">
        <p> Saindo de {{ corrida.carona.local_partida }} ({{ corrida.carona.horario_partida }})
            para {{ corrida.carona.local_chegada }} ({{ corrida.carona.horario_chegada }}) || Vagas: {{ corrida.vagas }}
        </p>
        <a href="{% url 'passageiro:detail' user.id corrida.id %}">Ver detalhes</a>
        <form method="post" action="{% url 'passageiro:request' user.id corrida.id%}">
            {% csrf_token %}
            <button
            {% if corrida.exists %}disabled{% endif %}
            {% if not corrida.exists %}type="submit"{% endif %}>
            {{corrida.title}}
            </button>
        </form>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrada nenhuma corrida para a busca</p>
{% endif %}

<a class="voltar" href="{% url 'passageiro:initial' user.id %}">Voltar</a>
{% endblock content %}