Caronusp/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static 
from django.views.generic import TemplateView
from django.urls import path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('accounts/', include('accounts.urls')),
    path('condutor/', include('condutor.urls')),
    path('passageiro/', include('passageiro.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls')),
    path('react/', TemplateView.as_view(template_name='front-end/index.html')),
    path('api/v1/', include('api.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('<int:usuario_id>/', views.afterlogin, name='afterlogin'),
    path('signup/condutor/<int:usuario_id>/', views.signCondutor, name='condutor'),
    path('signup/passageiro/<int:usuario_id>/', views.signPassageiro, name='passageiro'),
    path('loginredirect/', views.my_view, name='loginredirect')
]

api/urls.py
from django.urls import path
from .views import CaronaDetail, CaronaList

urlpatterns = [
    path('carona/<int:pk>/', CaronaDetail.as_view()),
    path('carona/', CaronaList.as_view()),
]

chat/urls.py
from django.urls import path
from .views import chat_corrida

app_name = 'chat'

urlpatterns = [
    path('<int:usuario_id>/chat_corrida/<int:corrida_id>/<int:type_actor>', chat_corrida, name='chat_corrida'),
]

condutor/urls.py
from django.urls import path

from . import views

app_name = 'condutor'

urlpatterns = [
    path('<int:usuario_id>', views.initial, name='initial'),
    path('<int:usuario_id>/edit/', views.UpdateView, name='edit_perfil'),
    path('<int:usuario_id>/create_carona', views.create_carona, name='create_carona'),
    path('<int:usuario_id>/list_corridas', views.list_corridas, name='list_corridas'),
    path('<int:usuario_id>/carona/<int:carona_id>', views.detail_carona, name='detail_carona'),
    path('<int:usuario_id>/notificacoes/<int:notificacao_id>', views.read_notificacao, name='read_notificacao'),
    path('<int:usuario_id>/carona/<int:carona_id>/edit', views.edit_carona, name='edit_carona'),
    path('<int:usuario_id>/carona/<int:carona_id>/edit', views.edit_carona, name='edit_carona'),
    path('<int:usuario_id>/corrida/<int:corrida_id>/delete', views.delete_corrida, name='delete_corrida'),
    path('<int:usuario_id>/carona/<int:carona_id>/create_corrida', views.create_corrida, name='create_corrida'),
    path('<int:usuario_id>/corrida/<int:corrida_id>/aceitar_passageiro_corrida/<int:passageiro_id>', views.aceitar_passageiro_corrida, name='aceitar_passageiro_corrida'),
    path('<int:usuario_id>/corrida/<int:corrida_id>/rejeitar_passageiro_corrida/<int:passageiro_id>', views.rejeitar_passageiro_corrida, name='rejeitar_passageiro_corrida'),
    path('<int:usuario_id>/corrida/<int:corrida_id>/encerrar_corrida', views.encerrar_corrida, name='encerrar_corrida'),
    path('<int:usuario_id>/corrida/<int:corrida_id>/avalia_passageiro_individual/<int:passageiro_id>', views.avalia_passageiro_individual, name='avalia_passageiro_individual'),
    path('<int:usuario_id>/passageirodetail/<int:passageiro_id>', views.passageirodetail, name='passageirodetail'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager

class UsuarioManager(BaseUserManager):
    use_in_migrations = True

    def create_user(self, email, username, password, **extra_fields):
        if not email:
            raise ValueError('Users must have an email address')
        user = self.model(email=self.normalize_email(email), username=username,  **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is False:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is False:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(email, username, password, **extra_fields)
    
class Usuario(AbstractUser):
    telefone = models.CharField(max_length=11)
    RG = models.CharField(max_length=9)
    foto = models.ImageField(upload_to="uploads/")
    is_condutor = models.BooleanField(default=False)
    is_passageiro = models.BooleanField(default=False)
    objects = UsuarioManager()
    
class Condutor(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    nota_media = models.FloatField()
    CNH = models.CharField(max_length=11)
    
    def __str__(self):
        return f'"{self.id}" - {self.usuario}'
    
class Passageiro(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    nota_media = models.FloatField()
    
    def __str__(self):
        return f'"{self.id}" - {self.usuario}'
    
class Carona(models.Model):
    condutor = models.ForeignKey(Condutor, on_delete=models.CASCADE)
    local_partida = models.TextField()
    endereco_partida = models.TextField()
    placeId_partida = models.TextField()
    local_chegada = models.TextField()
    endereco_chegada = models.TextField()
    placeId_chegada = models.TextField()
    horario_partida = models.TimeField()
    horario_chegada = models.TimeField()
    lugares = models.IntegerField()
    placa_veiculo = models.CharField(max_length=7)

    def __str__(self):
        return f'"{self.id}" - {self.condutor} - {self.local_partida} - {self.local_chegada} - {self.horario_partida} - {self.horario_chegada} - {self.lugares} - {self.placa_veiculo}'
    
class Corrida(models.Model):
    carona = models.ForeignKey(Carona, on_delete=models.CASCADE)
    dia = models.DateField()
    ativa = models.BooleanField()
    vagas = models.IntegerField()

    def __str__(self):
        return f'"{self.id}" - {self.carona} - {self.dia} - {self.ativa} - {self.vagas}'

class Passageiros_corrida(models.Model):
    passageiro = models.ForeignKey(Passageiro, on_delete=models.CASCADE)
    corrida = models.ForeignKey(Corrida, on_delete=models.CASCADE)
    aceito = models.BooleanField(null=True)

    def __str__(self):
        return f'"{self.id}" - {self.passageiro} - {self.corrida} - {self.aceito}'

class Avaliacao_Condutor(models.Model):
    avaliador = models.ForeignKey(Passageiro, on_delete=models.CASCADE)
    avaliado = models.ForeignKey(Condutor, on_delete=models.CASCADE)
    corrida = models.ForeignKey(Corrida, on_delete=models.CASCADE)
    nota = models.IntegerField()

    def __str__(self):
        return f'"{self.id}" - {self.avaliador} - {self.avaliado} - {self.corrida} - {self.nota}'
    
class Avaliacao_Passageiro(models.Model):
    avaliador = models.ForeignKey(Condutor, on_delete=models.CASCADE)
    avaliado = models.ForeignKey(Passageiro, on_delete=models.CASCADE)
    corrida = models.ForeignKey(Corrida, on_delete=models.CASCADE)
    nota = models.IntegerField()

    def __str__(self):
        return f'"{self.id}" - {self.avaliador} - {self.avaliado} - {self.corrida} - {self.nota}'
    
class Mensagem(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    corrida = models.ForeignKey(Corrida, on_delete=models.CASCADE)
    texto = models.TextField()
    hora = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'"{self.id}" - {self.usuario} - {self.corrida} - {self.texto} - {self.hora}'
    
class Notificacao(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    texto = models.TextField()
    hora = models.DateTimeField(auto_now_add=True)
    visto = models.BooleanField(default=False)
    para_condutor = models.BooleanField()

    def __str__(self):
        return f'"{self.id}" - {self.usuario} - {self.texto} - {self.hora} - {self.visto} - {self.para_condutor}'

staticpages/models.py
from django.db import models
from django.conf import settings


class Usuario(models.Model):
    # id = models.IntegerField()
    nome = models.CharField()
    email = models.CharField()
    telefone = models.CharField()
    hash_senha = models.CharField()
    RG = models.CharField()
    foto = models.ImageField()

    def __str__(self):
        return f'{self.nome}'

class Passageiro(models.Model):
    # id = models.IntegerField()
    usuario_id = models.ForeignKey(Usuario)
    nota_media = models.FloatField()

    def __str__(self):
        return f'"{self.id}" - {self.usuario_id}'
    
class Condutor(models.Model):
    # id = models.IntegerField()
    usuario_id = models.ForeignKey(Usuario)
    nota_media = models.FloatField()
    CNH = models.IntegerField()

    def __str__(self):
        return f'"{self.id}" - {self.usuario_id}'

class Carona(models.Model):
    # id = models.IntegerField()
    condutor_id = models.ForeignKey(Condutor)
    local_partida = models.CharField()
    local_chegada = models.CharField()
    horario_partida = models.TimeField()
    horario_chegada = models.TimeField()
    lugares = models.IntegerField()
    placa_veiculo = models.CharField()

    def __str__(self):
        return f''
    
class Corrida(models.Model):
    # id = models.IntegerField()
    carona_id = models.ForeignKey(Carona)
    dia = models.DateField()
    ativa = models.BooleanField()
    vagas = models.IntegerField()

    def __str__(self):
        return f''
    
class Passageiros_corrida(models.Model):
    # id = models.IntegerField()
    passageiro_id = models.ForeignKey(Passageiro)
    corrida_id = models.ForeignKey(Corrida)
    aceito = models.BooleanField()

    def __str__(self):
        return f''

class Avaliacao_Condutor(models.Model):
    # id = models.IntegerField()
    avaliador_id = models.ForeignKey(Passageiro)
    avaliado_id = models.ForeignKey(Condutor)
    corrida_id = models.ForeignKey(Corrida)
    nota = models.IntegerField()

    def __str__(self):
        return f''

class Avaliacao_Passageiro(models.Model):
    # id = models.IntegerField()
    avaliador_id = models.ForeignKey(Condutor)
    avaliado_id = models.ForeignKey(Passageiro)
    corrida_id = models.ForeignKey(Corrida)
    nota = models.IntegerField()

    def __str__(self):
        return f''
    
class Mensagem(models.Model):
    # id = models.IntegerField()
    usuario_id = models.ForeignKey(Usuario)
    corrda_id = models.ForeignKey(Corrida)
    texto = models.CharField()
    hora = models.DateTimeField()

    def __str__(self):
        return f''

condutor/templates/condutor/avalia_passageiros_corrida.html
{% extends 'base.html' %}

{% block title %}
Avaliar passageiros
{% endblock title %}

{% block content %}

<h1>Avalie seus passageiros</h1>
{% if passageiros_corrida %}
{% for passageiro in passageiros_corrida %}
<p>{{passageiro.passageiro.usuario.first_name}} {{passageiro.passageiro.usuario.last_name}} 
  em relação a corrida do dia {{corrida.dia}}</p>


<form method="post" action="{% url 'condutor:avalia_passageiro_individual' user.id corrida.id passageiro.passageiro.id %}">
  {% csrf_token %}
  <label for="id_nota">Nota:</label>
  <div class="rating">
    <input type="radio" name="nota" value="5" id="star5" /><label for="star5" title="5 estrelas"></label>
    <input type="radio" name="nota" value="4" id="star4" /><label for="star4" title="4 estrelas"></label>
    <input type="radio" name="nota" value="3" id="star3" /><label for="star3" title="3 estrelas"></label>
    <input type="radio" name="nota" value="2" id="star2" /><label for="star2" title="2 estrelas"></label>
    <input type="radio" name="nota" value="1" id="star1" /><label for="star1" title="1 estrela"></label>
  </div>
  <button type="submit">Avaliar</button>
</form>

<br>
{% endfor %}
{% else %}
<h3>Todos passageiros já foram avaliados.</h3>
<a class="voltar" href="{% url 'condutor:detail_carona' user.id corrida.carona.id %}">Voltar</a>
{% endif %}
{% endblock content %}

condutor/templates/condutor/create_carona.html
{% extends 'base.html' %}

{% block title %}
Criar carona
{% endblock title %}

{% block content %}
<h2>Publicar carona</h2>
<form method="post" action="{% url 'condutor:create_carona' user.id%}">
  {% csrf_token %}
  <p>
    <label for="id_local_partida">Local de partida:</label>
        <input type="text" name="local_partida" id="id_local_partida" required/>
      </p>
      <p>
        <label for="id_horario_partida">Horário de partida:</label>
        <input type="time" name="horario_partida" id="id_horario_partida" required/>
    </p>
    <p>
      <label for="id_local_chegada">Local de chegada:</label>
      <input type="text" name="local_chegada" id="id_local_chegada" required/>
    </p>
    <p>
      <label for="id_horario_chegada">Horário de chegada:</label>
      <input type="time" name="horario_chegada" id="id_horario_chegada" required/>
    </p>
    <p>
      <label for="id_vagas">Vagas disponíveis no carro:</label>
      <input type="number" name="vagas" id="id_vagas" required/>
    </p>
    <p>
      <label for="id_placa">placa do carro:</label>
        <input maxlength='7'  type="text" name="placa" id="id_placa" required/>
    </p>
    <p>
        <label for="num_corridas">Número de corridas:</label>
        <input type="number" id="num_corridas" name="num_corridas" min="1" required onchange="addDayFields()">
    </p>
    <p>
      <div id="diasFields" class="hidden">
        <p>
          <label for="dias"></label>
        </p>
        <br>
      </div>
    </p>
    
    
    <button type="submit">Criar</button>
    <a class="exit" href="{% url 'condutor:initial' user.id%}">Cancelar</a>
  </form>

  
  <script>
    function addDayFields() {
      const num_corridas = document.getElementById('num_corridas').value;
      const diasFields = document.getElementById('diasFields');
      const hoje = new Date().toISOString().split('T')[0]
      
      // Limpar campos antigos
      diasFields.innerHTML = '';
      
      // Adicionar novos campos com base no número de dias
      for (let i = 1; i <= num_corridas; i++) {
        const label = document.createElement('label');
        label.textContent = `Dia da corrida ${i}: `;
        
        const input = document.createElement('input');
        input.type = 'date';
        input.name = `day_${i}`;
        input.min = hoje;
        
        const lineBreak = document.createElement('br');
        
          // Adicionar os elementos ao formulário
          diasFields.appendChild(label);
          diasFields.appendChild(input);
          diasFields.appendChild(lineBreak);
      }

      // Mostrar os campos
      diasFields.classList.remove('hidden');
  }
</script>

{% endblock content %}

condutor/templates/condutor/create_corrida.html
{% extends 'base.html' %}

{% block title %}
Criar corrida
{% endblock title %}

{% block content %}

<form class="flex2" method="POST" action="{% url 'condutor:create_corrida' user.id carona.id %}">
  {% csrf_token %}
  <label for="dia">Selecione o dia da nova corrida:</label>
  <input type="date" id="dia" name="dia" min="{{ hoje }}" required>
  <button type="submit">Executar</button>
</form>
<a class="voltar" href="{% url 'condutor:detail_carona' user.id carona.id%}">Voltar para a tela da carona</a>

<script>
  var hoje = new Date().toISOString().split('T')[0];
  document.getElementById("dia").min = hoje;
</script>

{% endblock content %}

condutor/templates/condutor/delete_corrida.html
{% extends 'base.html' %}

{% block title %}
Deletar corrida
{% endblock title %}

{% block content %}

  <form class="flex2" method="POST" action="{% url 'condutor:delete_corrida' user.id corrida.id %}">
    {% csrf_token %}
    <p>
      Confirmar - Deletar a corrida do dia {{corrida.dia}}?
    </p>
    <button class="exit" type="submit">Cancelar</button>
  </form>
  <a class="voltar" href="{% url 'condutor:detail_carona' user.id corrida.carona.id%}">Voltar para a tela da carona</a>

{% endblock content %}

condutor/templates/condutor/detail_carona.html
{% extends 'base.html' %}

{% block title %}
Detalhes da carona
{% endblock title %}

{% block content %}

<h1> Carona </h1>
<h3>
  Local de partida {{ carona.local_partida }}  
  <br>
  Horario de partida {{carona.horario_partida}}
  <br>
  Local de chegada {{ carona.local_chegada }}  
  <br>
  Horario de chegada {{carona.horario_chegada}}
  <br>
  Placa {{carona.placa_veiculo}}
  <br>
</h3>
<div class="flex2">
  <a href="{% url 'condutor:edit_carona' user.id carona.id %}">Editar detalhes da carona</a>
  <a href="{% url 'condutor:create_corrida' user.id carona.id %}">Criar nova corrida nesta carona</a>
</div>

<h1> Corridas ativas dessa carona </h1>

{% for info_corrida in info_corridas_passageiros %}
  <h2>corrida do dia {{ info_corrida.corrida.dia }} </h2>

  <div class="flex2">
  <a href="{% url 'chat:chat_corrida' user.id info_corrida.corrida.id 0 %}"> Chat </a>
  <a class="voltar" href="{% url 'condutor:encerrar_corrida' user.id info_corrida.corrida.id %}">Encerrar corrida</a>
  <a class="exit" href="{% url 'condutor:delete_corrida' user.id info_corrida.corrida.id %}">Cancelar corrida</a>
  </div>

  <h3>Passageiros da corrida</h3>
  {% if info_corrida.passageiros_aceitos %}
    {% for passageiro_aceito in info_corrida.passageiros_aceitos %}
    <div class="flex2">
      <p>{{passageiro_aceito.usuario.first_name}} {{passageiro_aceito.usuario.last_name}}, Telefone: {{passageiro_aceito.usuario.telefone}}, Nota {{passageiro_aceito.nota_media}}</p>
      <a class="flex" href="{% url 'condutor:passageirodetail' user.id passageiro_aceito.id %}">Ver perfil</a>
    </div>
    {% endfor %}
  {% else %}
    <p>Sem passageiros</p>
  {% endif %}

  <h3>Passageiros solicitando entrada</h3>
  {% if info_corrida.passageiros_a_aceitar %}
    {% for passageiro_solicitante in info_corrida.passageiros_a_aceitar %}
    <div class="flex">
      <p>{{passageiro_solicitante.usuario.first_name}} {{passageiro_solicitante.usuario.last_name}}, Telefone: {{passageiro_solicitante.usuario.telefone}}, Nota: {{passageiro_solicitante.nota_media}}</p>
      <a class="flex" href="{% url 'condutor:passageirodetail' user.id passageiro_solicitante.id %}">Ver perfil</a>
      <a href="{% url 'condutor:aceitar_passageiro_corrida' user.id info_corrida.corrida.id passageiro_solicitante.id %}">Aceitar</a>
      <a class="exit" href="{% url 'condutor:rejeitar_passageiro_corrida' user.id info_corrida.corrida.id passageiro_solicitante.id %}">Rejeitar</a>
    </div>
    {% endfor %}
    {% else %}
    <p>Sem solicitações</p>
  {% endif %}

  {% endfor %}
  <a class="voltar" href="{% url 'condutor:initial' user.id %}">Voltar</a>
{% endblock content %}

condutor/templates/condutor/detail_passageiro.html
{% extends 'base.html' %}

{% block title %}
    Detalhes do passageiro
{% endblock %}

{% block content %}
<h1>Detalhes do passageiro</h1>
<p>Foto: <img src="{{ passageiro.usuario.foto.url }}" style="max-width: 450px; max-height: 300px"></p>
<p>Nome: {{ passageiro.usuario.first_name }} {{ passageiro.usuario.last_name }}</p>
<p>Telefone: {{ passageiro.usuario.telefone }}</p>
<p>Nota: {{ passageiro.nota_media }}</p>

<a class="voltar" onclick="history.back()">Voltar</a>
{% endblock %}

condutor/templates/condutor/edit_carona.html
{% extends 'base.html' %}

{% block title %}
Editar carona
{% endblock title %}

{% block content %}
<h2>Atualizar dados da carona</h2>
<form method="post" action="{% url 'condutor:edit_carona' user.id carona.id%}">
  {% csrf_token %}
  <p>
      <label for="id_local_partida">Local de partida:</label>
      <input type="text" name="local_partida" id="id_local_partida" value="{{carona.local_partida}}"/>
  </p>
  <p>
      <label for="id_horario_partida">Horário de partida:</label>
      <input type="time" name="horario_partida" id="id_horario_partida" value="{{horario_partida_formatado}}"/>
  </p>
  <p>
      <label for="id_local_chegada">Local de chegada:</label>
      <input type="text" name="local_chegada" id="id_local_chegada" value="{{carona.local_chegada}}"/>
  </p>
  <p>
      <label for="id_horario_chegada">Horário de chegada:</label>
      <input type="time" name="horario_chegada" id="id_horario_chegada" value="{{horario_chegada_formatado}}"/>
  </p>
  <p>
      <label for="id_placa">placa do carro:</label>
      <input type="text" name="placa" id="id_placa" value="{{carona.placa_veiculo}}"/>
  </p>
    
  
  <button type="submit">Salvar alterações</button>
  <a class="exit" href="{% url 'condutor:detail_carona' user.id carona.id%}">Cancelar</a>
</form>

{% endblock content %}

condutor/templates/condutor/edit_perfil.html
{% extends 'base.html' %}

{% block title %}
Editar perfil
{% endblock title %}

{% block content %}
<h1>Atualizar dados do perfil</h1>
<form method="post" enctype="multipart/form-data" action="{% url 'condutor:edit_perfil' usuario.id%}">
  {% csrf_token %}
    <p>
        <label for="id_foto">Foto:</label>
        <img src="{{ usuario.foto.url }}" style="max-width: 450px; max-height: 300px">
        <input type="file" name="foto" id="id_foto" value="{{usuario.foto.url}}"/>
    </p>
    <p>
        <label for="id_username">Nome de usuário:</label>
        <input type="text" name="username" id="id_username" value="{{usuario.username}}" />
    </p>
    <p>
        <label for="id_first_name">Nome:</label>
        <input type="text" name="first_name" id="id_first_name" value="{{usuario.first_name}}" />
    </p>
    <p>
        <label for="id_last_name">Sobrenome:</label>
        <input type="text" name="last_name" id="id_last_name" value="{{usuario.last_name}}" />
    </p>
    <p>
        <label for="id_email">Email:</label>
        <input type="text" name="email" id="id_email" value="{{usuario.email}}" />
    </p>
    <p>
        <label for="id_telefone">Telefone:</label>
        <input maxlength=11 type="text" name="telefone" id="id_telefone" value="{{usuario.telefone}}" />
    </p>
    <p>
        <label for="id_RG">RG:</label>
        <input maxlength=9 type="text" name="RG" id="id_RG" value="{{usuario.RG}}" />
    </p>
    <p>
        <label for="id_CNH">CNH:</label>
        <input maxlength=11 type="text" name="CNH" id="id_CNH" value="{{condutor.CNH}}" />
    </p>

    
  
    <button type="submit">Salvar alterações</button>
  <a class="exit" href="{% url 'condutor:initial' user.id%}">Cancelar</a>
</form>

{% endblock content %}

condutor/templates/condutor/initial.html
{% extends 'base.html' %}

{% block title %}
Condutor
{% endblock title %}

{% block content %}

<h1>Olá {{ user.first_name }} {{ user.last_name }}! Você está logado como condutor</h1>
<h1>Minhas caronas</h1>
{% if caronas %}
    {% for carona in caronas %}
        <div class="flex2">
            <p>Carona saindo de {{ carona.local_partida }} às {{carona.horario_partida}} para
                {{ carona.local_chegada }} às {{carona.horario_chegada}}
            </p>
            <a class="flex" href="{% url 'condutor:detail_carona' user.id carona.id %}">Ver detalhes</a>
        </div>
    {% endfor %}
{% else %}
    <p>Você não tem nenhuma carona ativa.</p>
{% endif %}
<h1>Ações</h1>
<div class="grid">
    <a href="{% url 'condutor:list_corridas' user.id %}">Ver histórico de corridas</a>
    <p>Aqui você pode ver as suas corridas finalizadas</p>
    <a href="{% url 'condutor:create_carona' user.id %}">Criar carona</a>
    <p>Criar uma carona para ir e voltar até onde quiser</p>
    <a href="{% url 'condutor:edit_perfil' user.id %}">Editar perfil</a>
    <p>Editar suas informações pessoais</p>
    <a href="{% url 'accounts:afterlogin' user.id %}">Escolher ator</a>
    <p>Voltar para a tela de escolha de login</p>
</div>


{% if notificacoes %}
    <h1>Notificações</h1>
    {% for notificacao in notificacoes %}
        <div class="notificacao" >
            <label class="flex"></label>
            <p>{{ notificacao.texto }}</p>
            <a href="{% url 'condutor:read_notificacao' user.id notificacao.id %}">Marcar como lida</a>
        </div>
    {% endfor %}
{% endif %}


{% endblock content %}

condutor/templates/condutor/list_corridas.html
{% extends 'base.html' %}

{% block title %}
Histórico de corridas
{% endblock title %}

{% block content %}
    <h1>Histórico de corridas {{ title }}</h1>
    {% if corrida_list %}
        <section>
        {% for corrida in corrida_list %}
            <article class="flex">
                <p>Corrida em {{ corrida.dia }} saindo de {{corrida.carona.local_partida}} às {{corrida.carona.horario_partida}} 
                    para {{corrida.carona.local_chegada}} às {{corrida.carona.horario_chegada}} || Placa: {{corrida.carona.placa_veiculo}}</p>
            </article>
        {% endfor %}
        </section>
        {% else %}
        <p>Você não tem corridas para essa categoria.</p>
    {% endif %}
    <a class="voltar" href="{% url 'condutor:initial' user.id %}"> Voltar</a>
{% endblock %}